#ifndef MY_LIBRARY_VERSION_H
#define MY_LIBRARY_VERSION_H

#define MY_LIBRARY_VERSION_MAJOR 1
#define MY_LIBRARY_VERSION_MINOR 0
#define MY_LIBRARY_VERSION_PATCH 0

#define MY_LIBRARY_VERSION_STRING "1.0.0"

#endif // MY_LIBRARY_VERSION_H